
[platformio]
default_envs = nodemcuv2-ota

[env:common]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_flags = -Iinclude -Isrc/classes
lib_deps =
    ModbusClient=https://github.com/eModbus/eModbus.git
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.6
monitor_speed = 115200

[env:nodemcuv2-usb]
extends = env:common
upload_protocol = esptool

[env:nodemcuv2-ota]
extends = env:common
upload_protocol = espota
upload_port = 192.168.12.118
upload_flags =
    --auth="StiebelPumpControl"
    --port=8266
    --host_ip=192.168.10.237